version: 9.0.{build} 
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2022

before_build:
  - cmd: dotnet restore stellar-asset-sdk.sln
  - cmd: dotnet tool restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"
artifacts:
  - path: 'stellar-asset-sdk\**\*.nupkg'
    name: nuget
  - path: 'stellar-asset-sdk-xdr\**\*.nupkg'
    name: nuget
build:
  project: stellar-asset-sdk.sln
  parallel: true
  verbosity: minimal
test_script:
  - cmd: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:ExcludeByFile=\"../stellar-asset-sdk/chaos.nacl/**/*.cs\" -p:ExcludeByFile=\"../stellar-asset-sdk-xdr/generated/*.cs\" ./stellar-asset-sdk-test --test-adapter-path:. --logger:Appveyor
after_test:
  - cmd: packages\coveralls.io\1.4.2\tools\coveralls.net.exe --opencover "./stellar-asset-sdk-test/coverage.opencover.xml" -r %COVERALLS_REPO_TOKEN%
deploy:
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
  provider: NuGet
  api_key:
    secure: s3Ldue+th/hm7rV3x4mKt/DgyqSrNHYYxk4cPQPeKmkfHNinH4KcJkNjjICtT91p
  skip_symbols: false
  artifact: nuget
