name: Pack and Test
on:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - opened
      - synchronize
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{github.workspace}}/nuget
  STELLAR_TEST_RPC_URL: http://localhost:8000/soroban/rpc
defaults:
  run:
    shell: pwsh
jobs:
  pack_and_test:
    runs-on: ubuntu-latest
    services:
      rpc:
        image: stellar/quickstart:testing
        ports:
          - 8000:8000
        env:
          ENABLE_LOGS: true
          ENABLE_SOROBAN_DIAGNOSTIC_EVENTS: true
          NETWORK: local
          PROTOCOL_VERSION: 22
        options: >-
          --health-cmd "curl --no-progress-meter --fail-with-body -X POST \"http://localhost:8000/soroban/rpc\" -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":8675309,\"method\":\"getNetwork\"}' && curl --no-progress-meter \"http://localhost:8000/friendbot\" | grep '\"invalid_field\": \"addr\"'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 50
    steps:
      - name: GitHub Ref
        run: |
          echo "GitHub Ref: ${{github.ref}}"
      - name: GitHub Head Ref
        run: |
          echo "GitHub Head Ref: ${{github.head_ref}}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Run tests
        run: dotnet test --configuration Release
      - name: Pack
        run: dotnet pack --configuration Release --output ${{env.NuGetDirectory}}